create extension if not exists pgcrypto;

create table if not exists mkt_novauniao.email_mkt_envio_historico (
  id bigint generated by default as identity primary key,
  run_id uuid not null default gen_random_uuid(),
  email text not null,
  email_norm text generated always as (lower(btrim(email))) stored,
  lote_key text,
  etapa integer not null check (etapa >= 1),
  campanha text not null,
  template_key text not null,
  status text not null default 'accepted' check (status in ('accepted', 'failed')),
  resend_email_id text,
  resend_response jsonb not null default '{}'::jsonb,
  data_envio timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists email_mkt_envio_hist_lote_etapa_uidx
  on mkt_novauniao.email_mkt_envio_historico (email_norm, lote_key, etapa)
  where status = 'accepted' and lote_key is not null;

create unique index if not exists email_mkt_envio_hist_template_uidx
  on mkt_novauniao.email_mkt_envio_historico (email_norm, template_key)
  where status = 'accepted';

create index if not exists email_mkt_envio_hist_lote_etapa_idx
  on mkt_novauniao.email_mkt_envio_historico (lote_key, etapa, data_envio);

create index if not exists email_mkt_envio_hist_email_idx
  on mkt_novauniao.email_mkt_envio_historico (email_norm, data_envio);

with lead_lotes as (
  select
    lower(btrim(email::text)) as email_norm,
    min(lower(regexp_replace(lote::text, '[^a-zA-Z0-9]', '', 'g'))) as lote_key
  from mkt_novauniao.email_mkt_leads
  where email is not null
    and btrim(email::text) <> ''
    and lote is not null
    and btrim(lote::text) <> ''
  group by lower(btrim(email::text))
)
insert into mkt_novauniao.email_mkt_envio_historico (
  email,
  lote_key,
  etapa,
  campanha,
  template_key,
  status,
  data_envio
)
select
  envio.email,
  lead_lotes.lote_key,
  1,
  envio.campanha,
  envio.campanha,
  'accepted',
  envio.data_envio
from mkt_novauniao.email_mkt_envio as envio
left join lead_lotes
  on lead_lotes.email_norm = lower(btrim(envio.email))
where envio.numero_envios > 0
on conflict do nothing;
